"""empty message

Revision ID: 25302b802fca
Revises: 7b41832f6810
Create Date: 2020-10-09 13:47:56.568525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25302b802fca'
down_revision = '7b41832f6810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
