"""empty message

Revision ID: e863d455b592
Revises: 9639a1c20da8
Create Date: 2020-10-09 07:16:25.678134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e863d455b592'
down_revision = '9639a1c20da8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_describtion', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_describtion')
    # ### end Alembic commands ###
